export const offers = [
    "Bank Offer Get ₹25* instant discount for the 1st ShoppingKart Order using ShoppingKart UPI",
    "Bank Offer 10% off on HSBC Bank Credit Card EMI Transactions, up to ₹1,500 on orders of ₹10,000 and above",
    "Bank Offer Flat ₹2,500 off on ICICI Bank Credit EMI Transactions, upto ₹2,500 on orders of ₹50,000 and above",
    "Special Price Get extra ₹13000 off (price inclusive of cashback/coupon)",
    "Partner Offer Sign-up for ShoppingKart Pay Later & get free Times Prime Benefits worth ₹10,000*",
    "Bank Offer Flat ₹1,250 off on ICICI Bank Debit Card EMI Transactions, on orders of ₹30,000 and above",
    "Bank Offer ₹2000 Off On Selected Banks Credit and Debit Card Transactions",
    "Bank Offer Flat ₹750 off on OneCard Credit Card EMI Transactions on orders of ₹12,500 and above",
    "Bank Offer Extra ₹750 off on HSBC Bank Credit Card EMI Transactions on products priced ₹29,990 and above",
    "Bank Offer Extra ₹1,500 off on HSBC Bank Credit Card EMI Transactions on products priced ₹49,990 and above",
    "Bank Offer Extra ₹1,250 off on IDFC FIRST Bank Credit Card EMI Txns on a Net Cart Value of ₹29,990 and above",
    "No cost EMI ₹7,834/month. Standard EMI also available",
    "Bank Offer 5% Cashback on ShoppingKart Axis Bank Card",
  ];