export const images = {
  slider1: require("../images/slider1.png"),
  slider2: require("../images/slider2.png"),
  slider3: require("../images/slider3.png"),
  frontpageoffer1: require("../images/frontpageoofer1.webp"),
  frontpageoffer2: require("../images/frontpageoffer2.webp"),
  frontpageoffer3: require("../images/frontpageoffer3.webp"),
  frontpageoffer4: require("../images/frontpageoffer4.webp"),
  frontpageoffer5: require("../images/frontpageoffer5.webp"),
  frontpageoffer6: require("../images/frontpageoffer6.webp"),
  productUpload1: require("../images/productUpload1.png"),
  productUpload2: require("../images/productUpload2.png"),
  OfferGrid1: require("../images/OfferGrid1.webp"),
  OfferGrid2: require("../images/OfferGrid2.webp"),
  OfferGrid3: require("../images/OfferGrid3.webp"),
  OfferGrid4: require("../images/OfferGrid4.webp"),
  OfferGrid5: require("../images/OfferGrid5.webp"),
  fAsssured: require("../images/fAsssured.png"),
  locationn: require("../images/location.png"),
  categoryNavbar: require("../images/categoryNavbar.png"),
};
