export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const FETCH_PRODUCTS= "FETCH_PRODUCTS"

export const FETCH_SPECIFIC_PRODUCTS = "FETCH_SPECIFIC_PRODUCTS"

export const FETCH_DATA_CATEGORY_WISE = "FETCH_DATA_CATEGORY_WISE"