export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

export const FETCH_PRODUCTS= "FETCH_PRODUCTS"

export const FETCH_SPECIFIC_PRODUCTS = "FETCH_SPECIFIC_PRODUCTS"

export const FETCH_DATA_CATEGORY_WISE = "FETCH_DATA_CATEGORY_WISE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"

export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"

export const FETCH_WISHLIST = "FETCH_WISHLIST"

export const ADD_TO_CART = "ADD_TO_CART"

export const FETCH_FROM_CART = "FETCH_FROM_CART"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const ADD_TOTALS = "ADD_TOTALS"